name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0 # Specify your Terraform version

      - name: Initialize Terraform
        run: |
          terraform init -chdir=terraform
        continue-on-error: false # Fail the workflow if this step fails

      - name: Validate Terraform
        run: |
          terraform validate -chdir=terraform
        continue-on-error: false # Fail the workflow if this step fails

      - name: Plan Terraform
        run: |
          terraform plan -chdir=terraform | tee plan.out
        continue-on-error: false # Fail the workflow if this step fails

      - name: Manual Approval
        if: github.event_name == 'push'
        uses: hmarr/auto-approve-action@v2 # Add a manual approval step
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Terraform
        if: github.event_name == 'push'
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: us-east-1 # Specify your AWS region
        run: |
          terraform apply -auto-approve -chdir=terraform
        continue-on-error: false # Fail the workflow if this step fails